public class J10_Subsets {
    //Find all distinct subsets from a normal set of numbers
    //Find all distinct subsets from a set which might contain duplicates
    //Given a set of numbers, find all of its permutations
    //Given a string, find all of its permutations preserving the character sequence but changing case.
    //Balanced Parenthesis
    /*
    Given a word, write a function to generate all of its unique generalized abbreviations.

Generalized abbreviation of a word can be generated by replacing each substring of the word by the count of characters in the substring.
Take the example of “ab” which has four substrings: “”, “a”, “b”, and “ab”.
After replacing these substrings in the actual word by the count of characters we get all the generalized abbreviations: “ab”, “1b”, “a1”, and “2”.
     */
    //Given an expression containing digits and operations (+, -, *),
    // find all possible ways in which the expression can be evaluated by grouping the numbers and operators using parentheses.
    //Structurally Unique Binary Search Trees (hard) #
    //Count of Structurally Unique Binary Search Trees (hard) #
}
